index:
    path: /
    controller: App\Controller\ContactController::contact
welcome:
    path: /welcome
    controller: App\Controller\WelcomeController::index
contact:
    path: /contact
    controller: App\Controller\ContactController::contact

 

    
    