App\Entity\Posts:
    type: entity
    table: posts
    indexes:
        fk_posts_users:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        content:
            type: text
            nullable: true
            length: 0
            options:
                fixed: false
        summary:
            type: text
            nullable: true
            length: 0
            options:
                fixed: false
        image:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    manyToOne:
        user:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
    