App\Entity\Users:
    type: entity
    table: users
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        password:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        email:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        isactive:
            type: boolean
            nullable: true
            column: isActive
    lifecycleCallbacks: {  }
